# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiCommonModelMessages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='OpenApiCommonModelMessages.proto',
  package='',
  syntax='proto2',
  serialized_options=_b('\n(com.xtrader.protocol.proto.commons.modelB\034ContainerCommonModelMessagesP\001\240\001\001'),
  serialized_pb=_b('\n OpenApiCommonModelMessages.proto*I\n\x10ProtoPayloadType\x12\x11\n\rPROTO_MESSAGE\x10\x05\x12\r\n\tERROR_RES\x10\x32\x12\x13\n\x0fHEARTBEAT_EVENT\x10\x33*\xf0\x01\n\x0eProtoErrorCode\x12\x11\n\rUNKNOWN_ERROR\x10\x01\x12\x17\n\x13UNSUPPORTED_MESSAGE\x10\x02\x12\x13\n\x0fINVALID_REQUEST\x10\x03\x12\x11\n\rTIMEOUT_ERROR\x10\x05\x12\x14\n\x10\x45NTITY_NOT_FOUND\x10\x06\x12\x16\n\x12\x43\x41NT_ROUTE_REQUEST\x10\x07\x12\x12\n\x0e\x46RAME_TOO_LONG\x10\x08\x12\x11\n\rMARKET_CLOSED\x10\t\x12\x1b\n\x17\x43ONCURRENT_MODIFICATION\x10\n\x12\x18\n\x14\x42LOCKED_PAYLOAD_TYPE\x10\x0b\x42M\n(com.xtrader.protocol.proto.commons.modelB\x1c\x43ontainerCommonModelMessagesP\x01\xa0\x01\x01')
)

_PROTOPAYLOADTYPE = _descriptor.EnumDescriptor(
  name='ProtoPayloadType',
  full_name='ProtoPayloadType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PROTO_MESSAGE', index=0, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_RES', index=1, number=50,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HEARTBEAT_EVENT', index=2, number=51,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=36,
  serialized_end=109,
)
_sym_db.RegisterEnumDescriptor(_PROTOPAYLOADTYPE)

ProtoPayloadType = enum_type_wrapper.EnumTypeWrapper(_PROTOPAYLOADTYPE)
_PROTOERRORCODE = _descriptor.EnumDescriptor(
  name='ProtoErrorCode',
  full_name='ProtoErrorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_ERROR', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNSUPPORTED_MESSAGE', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_REQUEST', index=2, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TIMEOUT_ERROR', index=3, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENTITY_NOT_FOUND', index=4, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CANT_ROUTE_REQUEST', index=5, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FRAME_TOO_LONG', index=6, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MARKET_CLOSED', index=7, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONCURRENT_MODIFICATION', index=8, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BLOCKED_PAYLOAD_TYPE', index=9, number=11,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=112,
  serialized_end=352,
)
_sym_db.RegisterEnumDescriptor(_PROTOERRORCODE)

ProtoErrorCode = enum_type_wrapper.EnumTypeWrapper(_PROTOERRORCODE)
PROTO_MESSAGE = 5
ERROR_RES = 50
HEARTBEAT_EVENT = 51
UNKNOWN_ERROR = 1
UNSUPPORTED_MESSAGE = 2
INVALID_REQUEST = 3
TIMEOUT_ERROR = 5
ENTITY_NOT_FOUND = 6
CANT_ROUTE_REQUEST = 7
FRAME_TOO_LONG = 8
MARKET_CLOSED = 9
CONCURRENT_MODIFICATION = 10
BLOCKED_PAYLOAD_TYPE = 11


DESCRIPTOR.enum_types_by_name['ProtoPayloadType'] = _PROTOPAYLOADTYPE
DESCRIPTOR.enum_types_by_name['ProtoErrorCode'] = _PROTOERRORCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
